### ISSUE TITLE
Upgrade to Vite 3

### ISSUE THREAD

**Issue by Akryum** [histoire-dev/histoire#189]
### Clear and concise description of the problem

Upgrade to Vite 3

### Suggested solution

N/A

### Alternative
N/A

### Additional context

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment]
https://stackblitz.com/edit/nuxt-starter-szzksv?file=package.json

**Comment by rromanv** [comment]
Yarn is giving me this warning
`warning " > histoire@0.8.4" has incorrect peer dependency "vite@^2.9.0".`

And npm I need to install with `--legacy-peer-deps` flag

**Comment by itpropro** [comment]
When using vite 3 with @vitejs/plugin-vue, I cannot build, as the build gets stuck at the following step:

```
vite v3.0.2 building for development...
transforming (144) ..\..\$histoire-search-title-data-resolved
```

When changing back to `"vite": "^2.9.1"` and `"@vitejs/plugin-vue": "^2.3.2",`, everything works fine again. Any plans to update the dependencies @Akryum?

**Comment by Akryum** [comment]
> Any plans to update the dependencies @Akryum?

Look at the title and description of this very issue :cat2:

**Comment by itpropro** [comment]
> > Any plans to update the dependencies @Akryum?
> 
> Look at the title and description of this very issue 🐈

My fault, I thought the issue was created by @rromanv 🙈 Just wanted to provide some information where it is stuck for me :)

**Comment by sapphi-red** [comment]
I checked this a bit and found `@histoire/app` is blocked by https://github.com/vitejs/vite/issues/9086.

**Comment by awacode21** [comment]
The Ticket got closed, is it solved and histoire vite 3.0.0 ready?

**Comment by Akryum** [comment]
Fixed in https://github.com/histoire-dev/histoire/commit/bdff4a471ee8fcbb86a78fdfe7eccdecabe0bdae

**Comment by rasc-br** [comment]
I still have the dependency issue, am I doing something wrong?
I did a fresh install in an empty folder to check, and the dependency is still there as vite 2.9.1
![image](https://user-images.githubusercontent.com/33508295/184182788-08582744-9f2c-41e6-9db3-f27b8c22397d.png)

**Comment by dotoleeoak** [comment]
@rasc-br @llbarre It seems the fix has not been published yet. We need to wait the next version, not 0.9.6.
