### ISSUE TITLE
Error with Nuxt v3.0.0-rc.9: Package import specifier "#build/app.config.mjs" is not defined in package

### ISSUE THREAD

**Issue by grmnn** [histoire-dev/histoire#286]
### Describe the bug

When using Histoire with Nuxt **v3.0.0-rc.9** there seems to be an issue with the built-in components like `<NuxtLink>`.  (Nuxt v3.0.0-rc.8 works fine)

1. Visit reproduction link
2. run `npm run dev` - everything should work fine. 
3. Uncomment the `<NuxtLink>` in the `BaseButton.vue` component and reload webcontainer.

Error occurs:
Error while collecting story /home/projects/nuxt-starter-sf9sq6/stories/BaseButton.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /home/projects/nuxt-starter-sf9sq6/node_modules/nuxt/package.json imported from /home/projects/nuxt-starter-sf9sq6/node_modules/nuxt/dist/app/config.mjs

There is also an issue in the Nuxt repo regarding this issue: https://github.com/nuxt/framework/issues/7244

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sf9sq6?file=components/BaseButton.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-nuxt: ^0.10.7 => 0.10.7 
    @histoire/plugin-vue: ^0.10.7 => 0.10.7 
    histoire: ^0.10.7 => 0.10.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Lyokolux** [comment]
I have the issue with a `.story.vue` file too.

```
Error while collecting story components/molecules/PwLinkInput.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in node_modules/nuxt/package.json imported from node_modules/nuxt/dist/app/config.mjs
    at new NodeError (node:internal/errors:371:5)
    at throwImportNotDefined (node:internal/modules/esm/resolve:429:9)
    at packageImportsResolve (node:internal/modules/esm/resolve:778:3)
    at moduleResolve (node:internal/modules/esm/resolve:924:21)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not.

**Comment by gmavors** [comment]
Hmm no, still the same error, tested on Stackblitz (but I am not able to get the latest edge release, it still states it is rc.9) 

And locally with edge release, still same error message with reference to rc.11

```shell
Error while collecting story /home/gmavors/dev/nue/stories/BaseIcon.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /home/gmavors/dev/nue/node_modules/.pnpm/nuxt3@3.0.0-rc.11-27727864.720da64_itqs5654cmlnjraw6gjzqacppi/node_modules/nuxt3/package.json imported from /home/gmavors/dev/nue/node_modules/.pnpm/nuxt3@3.0.0-rc.11-27727864.720da64_itqs5654cmlnjraw6gjzqacppi/node_modules/nuxt3/dist/app/config.mjs
    at new NodeError (node:internal/errors:372:5)
    at throwImportNotDefined (node:internal/modules/esm/resolve:422:9)
    at packageImportsResolve (node:internal/modules/esm/resolve:791:3)
    at moduleResolve (node:internal/modules/esm/resolve:944:16)
    at defaultResolve (node:internal/modules/esm/resolve:1166:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:536:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:250:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by danielroe** [comment]
You should be able to see it working in the stackblitz I linked.

**Comment by gmavors** [comment]
The BaseButton.vue component has a <NuxtLink> inside which is commented out, if I uncomment the <NuxtLink>, I still get the error.

**Comment by saschafuchs** [comment]
I have the problem too. In my case (current Nuxt 3 RC11) the error occurs when the component has a Pinia store included or I use `useRoute()`. `<NuxtLink>` works without problems.

**Comment by zoey-kaiser** [comment]
> I have the problem too. In my case (current Nuxt 3 RC11) the error occurs when the component has a Pinia store included or I use `useRoute()`. `<NuxtLink>` works without problems.

Same issue here: https://github.com/sidestream-tech/sidebase/pull/51

**Comment by danielroe** [comment]
If you are experiencing this error (with 'import specifier' error message), would you provide a reproduction? I cannot reproduce it.

As for the issue with `NuxtLink` in the sandbox above:

1. You did not define any `to` prop so `<NuxtLink v-if="to" :to="to" class="button"><slot /></NuxtLink>` would always fail to render and would likely also error.
2. `<NuxtLink>` depends on having nuxt context available so you likely need to stub this out in your project.

**Comment by grmnn** [comment]
Regarding the missing props, you were right. But when I use **rc.8**, I can use `<NuxtLink>`, with **rc.11**, an error occurs. 

`TypeError: Cannot read properties of undefined (reading '_observer')
    at useObserver (nuxt-link.mjs?v=8c5a6940:204:15)
    at setup (nuxt-link.mjs?v=8c5a6940:126:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7187:29)
    at setupComponent (runtime-core.esm-bundler.js:7142:11)
    at mountComponent (runtime-core.esm-bundler.js:5491:13)
    at processComponent (runtime-core.esm-bundler.js:5466:17)
    at patch (runtime-core.esm-bundler.js:5068:21)
    at mountChildren (runtime-core.esm-bundler.js:5252:13)
    at processFragment (runtime-core.esm-bundler.js:5425:13)`

So this should most likely be fixed in the `@histoire/plugin-nuxt` package or not?

**Comment by danielroe** [comment]
The change is that now, in nuxt core, `<NuxtLink>` depends on `useNuxtApp()` (in order to observe + prefetch links - https://github.com/nuxt/framework/pull/4329).

We are exploring ideas in Nuxt to make this easier to integrate with tools like Histoire, but until then you'll need to stub `NuxtLink`.

It's not a bug with Histoire; there are quite a lot of Nuxt core composables or components that depend on a broader Nuxt context. But possibly we could provide some built-in stubs in histoire - what do you think @Akryum?

**Comment by tobiashm** [comment]
I'm still getting this error with Nuxt 3.0.0-rc.11 and Histoire 0.11.3 :(

```
Error while collecting story /…/Something.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /…/node_modules/nuxt/package.json imported from /…/node_modules/nuxt/dist/app/config.mjs
    at new NodeError (node:internal/errors:393:5)
    at throwImportNotDefined (node:internal/modules/esm/resolve:329:9)
    at packageImportsResolve (node:internal/modules/esm/resolve:698:3)
    at moduleResolve (node:internal/modules/esm/resolve:853:16)
    at defaultResolve (node:internal/modules/esm/resolve:1074:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

Seems like something the Nuxt plug-in ought to take care of?

**Comment by danielroe** [comment]
@tobiashm A reproduction would be appreciated.

**Comment by tobiashm** [comment]
@danielroe I will try to isolate the issue. It appears that about 1/5 of our stories are _not_ affected by this, but I can't see what's different about the components in the ones that seems to work.

**Comment by Lyokolux** [comment]
> I'm still getting this error with Nuxt 3.0.0-rc.11 and Histoire 0.11.3 :(
> 
> ```
> Error while collecting story /…/Something.story.vue:
> TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /…/node_modules/nuxt/package.json imported from /…/node_modules/nuxt/dist/app/config.mjs
>     at new NodeError (node:internal/errors:393:5)
>     at throwImportNotDefined (node:internal/modules/esm/resolve:329:9)
>     at packageImportsResolve (node:internal/modules/esm/resolve:698:3)
>     at moduleResolve (node:internal/modules/esm/resolve:853:16)
>     at defaultResolve (node:internal/modules/esm/resolve:1074:11)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
>     at link (node:internal/modules/esm/module_job:75:36)
> ```
> 
> Seems like something the Nuxt plug-in ought to take care of?

Here some content:

It fails on 2 stories out of 50 to me. Both stories uses a common Vue Component.
I replaced the line with the `useFetch` and it works:
```
// const { data } = await useFetch(`/api/v1/links/generate/${cleanedValue}`, { key: new Date().toISOString() })
const data = ref()
```

**Comment by danielroe** [comment]
Yes, `useFetch` relies on the nuxt context. Surely this didn't ever work in histoire?

**Comment by grmnn** [comment]
As stated in the initial post of this issue, something changed in Nuxt RC.9 because stories with NuxtLink in it were working in Histoire with Nuxt RC.8. 

I've now again an issue when using the [Nuxt Icon Module](https://github.com/nuxt-modules/icon) since it also relies on the nuxt context, it is not working with Histoire and I again get these errors "package import specifier....".  Also I am not able to go back to RC.8 because the module needs atleast RC.9.

> We are exploring ideas in Nuxt to make this easier to integrate with tools like Histoire, but until then you'll need to stub `NuxtLink`.
> 
> It's not a bug with Histoire; there are quite a lot of Nuxt core composables or components that depend on a broader Nuxt context. But possibly we could provide some built-in stubs in histoire - what do you think @Akryum?

So until this is not resolved, we would need create workarounds for all components which rely directly on the nuxt context or use components which rely on it?

**Comment by T-Zahil** [comment]
Same issue for me when importing a component using the `<Icon>` from Nuxt Icon Module

**Comment by david8z** [comment]
Why is this closed if it is still happening?
