### ISSUE TITLE
Nuxt/image-edge + Histoire doesnt't work

### ISSUE THREAD

**Issue by JeremyMees** [histoire-dev/histoire#385]
### Describe the bug

- I have made a fresh nuxt project on stackblitz (and locally via Nuxt's "getting started" instructions)
- then installed histoire while following the getting started for nuxt
- then created a basic Button.vue and Button.story.vue, and got the following errors in console when clicking on the story:
![Screenshot 2022-12-02 at 08 05 24](https://user-images.githubusercontent.com/59842057/205235241-b7149ffd-e9f5-41de-aa7b-aa26e60d5a5f.png)

For used package manager - I use yarn locally but the reproduction stackblitz uses npm

### Reproduction

[StackBlitz](https://stackblitz.com/edit/nuxt-starter-fbr3jz?file=components%2FImage.vue,nuxt.config.ts)

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 7.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/Caches/fnm_multishells/43544_1669964830256/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/Library/Caches/fnm_multishells/43544_1669964830256/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 106.0.1
    Firefox Developer Edition: 108.0
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Bcavez** [comment]
@Akryum mentioned on discord that this should be fixed in 0.11.9 but sadly it is not. :(

**Comment by AnjaRoseBikes** [comment]
Hey @Akryum, unfortunately the update did not fix the bug.

I get the error: "500 $img is not a function"
And the Nuxt Layout ist rendert below every (working) Component Preview and below the Histoire Overview. 

In error case I get 500 page twice:
![Bildschirm­foto 2023-02-17 um 09 38 41](https://user-images.githubusercontent.com/108875697/219595104-52a4ad03-0105-4154-bd29-92e4bc72a806.png)

After scrolling down:
![Bildschirm­foto 2023-02-17 um 09 38 50](https://user-images.githubusercontent.com/108875697/219595136-5fd4eb0e-ad66-4259-af20-37176bfe7a82.png)

Reproducible here:
(Update to nuxt 3.2.0 and histoire 0.15.7)
[StackBlitz](https://stackblitz.com/edit/nuxt-starter-uys4vq?file=package.json,components%2FImage.vue,stories%2FImage.story.vue&file=nuxt.config.ts&issueNumber=385&issueRepo=histoire-dev/histoire
)

**Comment by AnjaRoseBikes** [comment]
With the new Nuxt Version I am only getting the Error "500 $img is not a function"

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-uys4vq?file=package.json)
(Update to nuxt 3.2.2 and histoire 0.15.8)
